Update update file function check choiced repository

diff --git a/src/Update b/src/Update
--- a/src/Update
+++ b/src/Update
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+function Check_Choiced_Repository() {
+    if [[ -f "Repository_Manager/src/.Update_Repositories/.Update_$1" ]]; then
+        FUNC="$1" ;;
+    else
+        echo -e "\nInvalid parameter. Try again"
+        exit 1
+        ;;
+    fi
+}
+
 PATH="GitRepositories"
 
 if [[ -z "$1" ]]; then
@@ -22,13 +32,7 @@ case $CHOICE in
         --all -> Update all your repositories"
         exit 0
         ;;
-    *) if [[ -f "Repository_Manager/src/.Update_Repositories/.Update_$CHOICE" ]]; then
-        FUNC="$CHOICE" ;;
-        else
-            echo -e "\nInvalid parameter. Try again"
-            exit 1
-            ;;
-        fi
+    *) Check_Choiced_Repository $CHOICE
 esac
 
 if [[ -f "Repository_Manager/src/.Update_Repositories/.Update_$FUNC" ]]; then
